// Bron van waarheid voor het Grieks-spel: het alfabet en de woordgroepen.
// De uitspraak in `zegmaar` is fonetisch Nederlands, bedoeld om voor te lezen.

export const LETTERS = [
  { hoofd: "Α", klein: "α", naam: "alfa",    grieks: "άλφα",    klank: "a zoals in bal" },
  { hoofd: "Β", klein: "β", naam: "vita",    grieks: "βήτα",    klank: "v zoals in vis" },
  { hoofd: "Γ", klein: "γ", naam: "gamma",   grieks: "γάμμα",   klank: "zachte g" },
  { hoofd: "Δ", klein: "δ", naam: "delta",   grieks: "δέλτα",   klank: "th zoals Engels this" },
  { hoofd: "Ε", klein: "ε", naam: "epsilon", grieks: "έψιλον",  klank: "e zoals in bed" },
  { hoofd: "Ζ", klein: "ζ", naam: "zita",    grieks: "ζήτα",    klank: "z zoals in zon" },
  { hoofd: "Η", klein: "η", naam: "ita",     grieks: "ήτα",     klank: "ie zoals in fiets" },
  { hoofd: "Θ", klein: "θ", naam: "thita",   grieks: "θήτα",    klank: "th zoals Engels think" },
  { hoofd: "Ι", klein: "ι", naam: "jota",    grieks: "ιώτα",    klank: "ie zoals in fiets" },
  { hoofd: "Κ", klein: "κ", naam: "kappa",   grieks: "κάππα",   klank: "k zoals in kat" },
  { hoofd: "Λ", klein: "λ", naam: "lamda",   grieks: "λάμδα",   klank: "l zoals in lamp" },
  { hoofd: "Μ", klein: "μ", naam: "mi",      grieks: "μι",      klank: "m zoals in maan" },
  { hoofd: "Ν", klein: "ν", naam: "ni",      grieks: "νι",      klank: "n zoals in neus" },
  { hoofd: "Ξ", klein: "ξ", naam: "ksi",     grieks: "ξι",      klank: "ks zoals in heks" },
  { hoofd: "Ο", klein: "ο", naam: "omikron", grieks: "όμικρον", klank: "o zoals in bos" },
  { hoofd: "Π", klein: "π", naam: "pi",      grieks: "πι",      klank: "p zoals in pop" },
  { hoofd: "Ρ", klein: "ρ", naam: "ro",      grieks: "ρο",      klank: "rollende r" },
  { hoofd: "Σ", klein: "σ", naam: "sigma",   grieks: "σίγμα",   klank: "s zoals in soep" },
  { hoofd: "Τ", klein: "τ", naam: "taf",     grieks: "ταυ",     klank: "t zoals in tak" },
  { hoofd: "Υ", klein: "υ", naam: "ipsilon", grieks: "ύψιλον",  klank: "ie zoals in fiets" },
  { hoofd: "Φ", klein: "φ", naam: "fi",      grieks: "φι",      klank: "f zoals in fee" },
  { hoofd: "Χ", klein: "χ", naam: "chi",     grieks: "χι",      klank: "ch zoals in lachen" },
  { hoofd: "Ψ", klein: "ψ", naam: "psi",     grieks: "ψι",      klank: "ps zoals in psst!" },
  { hoofd: "Ω", klein: "ω", naam: "omega",   grieks: "ωμέγα",   klank: "o zoals in bos" },
];

export const WOORDEN = {
  "👋 Hallo zeggen": [
    { grieks: "Γεια σου",   zegmaar: "JA-soe",         nl: "hallo / dag",  emoji: "👋" },
    { grieks: "Καλημέρα",   zegmaar: "ka-li-MÈ-ra",    nl: "goeiemorgen",  emoji: "🌞" },
    { grieks: "Καληνύχτα",  zegmaar: "ka-li-NIECH-ta", nl: "slaapwel",     emoji: "🌙" },
    { grieks: "Ευχαριστώ",  zegmaar: "ef-cha-ri-STO",  nl: "dank je",      emoji: "💛" },
    { grieks: "Παρακαλώ",   zegmaar: "pa-ra-ka-LO",    nl: "alsjeblieft",  emoji: "🎁" },
    { grieks: "Ναι",        zegmaar: "nè",             nl: "ja",           emoji: "✅" },
    { grieks: "Όχι",        zegmaar: "O-chie",         nl: "nee",          emoji: "❌" },
  ],
  "🔢 Tellen tot 10": [
    { grieks: "ένα",     zegmaar: "E-na",      nl: "een (1)",   emoji: "1️⃣" },
    { grieks: "δύο",     zegmaar: "THIE-o",    nl: "twee (2)",  emoji: "2️⃣" },
    { grieks: "τρία",    zegmaar: "TRIE-a",    nl: "drie (3)",  emoji: "3️⃣" },
    { grieks: "τέσσερα", zegmaar: "TES-se-ra", nl: "vier (4)",  emoji: "4️⃣" },
    { grieks: "πέντε",   zegmaar: "PEN-dè",    nl: "vijf (5)",  emoji: "5️⃣" },
    { grieks: "έξι",     zegmaar: "EK-si",     nl: "zes (6)",   emoji: "6️⃣" },
    { grieks: "επτά",    zegmaar: "ep-TA",     nl: "zeven (7)", emoji: "7️⃣" },
    { grieks: "οκτώ",    zegmaar: "ok-TO",     nl: "acht (8)",  emoji: "8️⃣" },
    { grieks: "εννέα",   zegmaar: "en-NE-a",   nl: "negen (9)", emoji: "9️⃣" },
    { grieks: "δέκα",    zegmaar: "THE-ka",    nl: "tien (10)", emoji: "🔟" },
  ],
  "🐾 Dieren": [
    { grieks: "γάτα",      zegmaar: "GA-ta",        nl: "kat",     emoji: "🐱" },
    { grieks: "σκύλος",    zegmaar: "SKIE-los",     nl: "hond",    emoji: "🐶" },
    { grieks: "ψάρι",      zegmaar: "PSA-rie",      nl: "vis",     emoji: "🐟" },
    { grieks: "πουλί",     zegmaar: "poe-LIE",      nl: "vogel",   emoji: "🐦" },
    { grieks: "άλογο",     zegmaar: "A-lo-go",      nl: "paard",   emoji: "🐴" },
    { grieks: "ελέφαντας", zegmaar: "e-LE-fan-das", nl: "olifant", emoji: "🐘" },
  ],
  "👨‍👩‍👧 Familie": [
    { grieks: "μαμά",    zegmaar: "ma-MA",      nl: "mama",  emoji: "👩" },
    { grieks: "μπαμπάς", zegmaar: "ba-BAS",     nl: "papa",  emoji: "👨" },
    { grieks: "αδελφή",  zegmaar: "a-thel-FIE", nl: "zus",   emoji: "👧" },
    { grieks: "αδελφός", zegmaar: "a-thel-FOS", nl: "broer", emoji: "👦" },
    { grieks: "γιαγιά",  zegmaar: "ja-JA",      nl: "oma",   emoji: "👵" },
    { grieks: "παππούς", zegmaar: "pa-POES",    nl: "opa",   emoji: "👴" },
  ],
};
